const productos = [
  {
    id: 100,
    img: "",
    categoria: "PC Armada",
    titulo: "PC Gamer ASUS ROG Strix GT15",
    precio: 1500,
    marca: "ASUS",
    tipo_producto: "PC de escritorio",
  },
  {
    id: 101,
    img: "",
    categoria: "PC Armada",
    titulo: "PC Gaming HP Omen 30L",
    precio: 1400,
    marca: "HP",
    tipo_producto: "PC de escritorio",
  },
  {
    id: 102,
    img: "",
    categoria: "PC Armada",
    titulo: "PC All-in-One Dell Inspiron 27",
    precio: 1100,
    marca: "Dell",
    tipo_producto: "PC de escritorio",
  },
  {
    id: 103,
    img: "",
    categoria: "PC Armada",
    titulo: "PC Gamer MSI Trident 3",
    precio: 1300,
    marca: "MSI",
    tipo_producto: "PC de escritorio",
  },
  {
    id: 104,
    img: "",
    categoria: "PC Armada",
    titulo: "PC Desktop Lenovo IdeaCentre 5i",
    precio: 1000,
    marca: "Lenovo",
    tipo_producto: "PC de escritorio",
  },
  {
    id: 105,
    img: "",
    categoria: "PC Armada",
    titulo: "PC Gaming Acer Predator Orion 3000",
    precio: 1200,
    marca: "Acer",
    tipo_producto: "PC de escritorio",
  },
  {
    id: 106,
    img: "",
    categoria: "PC Armada",
    titulo: 'PC All-in-One Apple iMac 24"',
    precio: 2000,
    marca: "Apple",
    tipo_producto: "PC de escritorio",
  },
  {
    id: 107,
    img: "",
    categoria: "PC Armada",
    titulo: "PC Gamer CyberPowerPC Gamer Xtreme VR",
    precio: 1600,
    marca: "CyberPowerPC",
    tipo_producto: "PC de escritorio",
  },
  {
    id: 108,
    img: "",
    categoria: "PC Armada",
    titulo: "PC Desktop Alienware Aurora R11",
    precio: 1800,
    marca: "Alienware",
    tipo_producto: "PC de escritorio",
  },
  {
    id: 109,
    img: "",
    categoria: "PC Armada",
    titulo: "PC Gaming SkyTech Blaze II",
    precio: 1250,
    marca: "SkyTech",
    tipo_producto: "PC de escritorio",
  },
  {
    id: 200,
    img: "",
    categoria: "Notebook",
    titulo: "Notebook ASUS ROG Zephyrus G14",
    precio: 1400,
    marca: "ASUS",
    tipo_producto: "Portátil",
  },
  {
    id: 201,
    img: "",
    categoria: "Notebook",
    titulo: "Notebook MSI GS66 Stealth",
    precio: 1600,
    marca: "MSI",
    tipo_producto: "Portátil",
  },
  {
    id: 202,
    img: "",
    categoria: "Notebook",
    titulo: "Notebook Dell XPS 13",
    precio: 1300,
    marca: "Dell",
    tipo_producto: "Portátil",
  },
  {
    id: 203,
    img: "",
    categoria: "Notebook",
    titulo: "Notebook HP Spectre x360",
    precio: 1500,
    marca: "HP",
    tipo_producto: "Portátil",
  },
  {
    id: 204,
    img: "",
    categoria: "Notebook",
    titulo: "Notebook Lenovo Yoga C940",
    precio: 1200,
    marca: "Lenovo",
    tipo_producto: "Portátil",
  },
  {
    id: 205,
    img: "",
    categoria: "Notebook",
    titulo: "Notebook Acer Swift 3",
    precio: 1100,
    marca: "Acer",
    tipo_producto: "Portátil",
  },
  {
    id: 206,
    img: "",
    categoria: "Notebook",
    titulo: "Notebook Apple MacBook Air",
    precio: 1800,
    marca: "Apple",
    tipo_producto: "Portátil",
  },
  {
    id: 207,
    img: "",
    categoria: "Notebook",
    titulo: "Notebook Razer Blade 15",
    precio: 2000,
    marca: "Razer",
    tipo_producto: "Portátil",
  },
  {
    id: 208,
    img: "",
    categoria: "Notebook",
    titulo: "Notebook Gigabyte Aero 15",
    precio: 1700,
    marca: "Gigabyte",
    tipo_producto: "Portátil",
  },
  {
    id: 209,
    img: "",
    categoria: "Notebook",
    titulo: "Notebook Microsoft Surface Laptop 4",
    precio: 1500,
    marca: "Microsoft",
    tipo_producto: "Portátil",
  },
  {
    id: 300,
    img: "",
    categoria: "Accesorio",
    titulo: "Teclado mecánico Corsair K95 RGB Platinum",
    precio: 180,
    marca: "Corsair",
    tipo_producto: "Teclado",
  },
  {
    id: 301,
    img: "",
    categoria: "Accesorio",
    titulo: "Mouse inalámbrico Logitech MX Master 3",
    precio: 100,
    marca: "Logitech",
    tipo_producto: "Mouse",
  },
  {
    id: 302,
    img: "",
    categoria: "Accesorio",
    titulo: "Auriculares gaming SteelSeries Arctis 7",
    precio: 150,
    marca: "SteelSeries",
    tipo_producto: "Auriculares",
  },
  {
    id: 303,
    img: "",
    categoria: "Accesorio",
    titulo: "Monitor ASUS ROG Swift PG279Q",
    precio: 700,
    marca: "ASUS",
    tipo_producto: "Monitor",
  },
  {
    id: 304,
    img: "",
    categoria: "Accesorio",
    titulo: "Alfombrilla para ratón Razer Goliathus",
    precio: 40,
    marca: "Razer",
    tipo_producto: "Alfombrilla",
  },
  {
    id: 305,
    img: "",
    categoria: "Accesorio",
    titulo: "Webcam Logitech C920",
    precio: 80,
    marca: "Logitech",
    tipo_producto: "Cámara web",
  },
  {
    id: 306,
    img: "",
    categoria: "Accesorio",
    titulo: "Silla gaming DXRacer Formula Series",
    precio: 300,
    marca: "DXRacer",
    tipo_producto: "Silla",
  },
  {
    id: 307,
    img: "",
    categoria: "Accesorio",
    titulo: "Micrófono Blue Yeti USB",
    precio: 150,
    marca: "Blue",
    tipo_producto: "Micrófono",
  },
  {
    id: 308,
    img: "",
    categoria: "Accesorio",
    titulo: "Router ASUS RT-AX86U",
    precio: 250,
    marca: "ASUS",
    tipo_producto: "Router",
  },
  {
    id: 309,
    img: "",
    categoria: "Accesorio",
    titulo: "Impresora HP OfficeJet Pro 9025",
    precio: 200,
    marca: "HP",
    tipo_producto: "Impresora",
  },
  {
    id: 400,
    img: "",
    categoria: "Componente de PC",
    titulo: "Memoria RAM Corsair Vengeance RGB Pro 16GB DDR4 3200MHz",
    precio: 80,
    marca: "Corsair",
    tipo_producto: "Memoria RAM",
  },
  {
    id: 401,
    img: "",
    categoria: "Componente de PC",
    titulo: "Tarjeta gráfica Gigabyte GeForce RTX 3060 Ti",
    precio: 500,
    marca: "Gigabyte",
    tipo_producto: "Tarjeta gráfica",
  },
  {
    id: 402,
    img: "",
    categoria: "Componente de PC",
    titulo: "Disco SSD Samsung 970 EVO Plus 1TB",
    precio: 150,
    marca: "Samsung",
    tipo_producto: "Disco SSD",
  },
  {
    id: 403,
    img: "",
    categoria: "Componente de PC",
    titulo: "Procesador AMD Ryzen 9 5900X",
    precio: 600,
    marca: "AMD",
    tipo_producto: "Procesador",
  },
  {
    id: 404,
    img: "",
    categoria: "Componente de PC",
    titulo: "Placa base ASUS ROG Strix X570-E Gaming",
    precio: 300,
    marca: "ASUS",
    tipo_producto: "Placa base",
  },
  {
    id: 405,
    img: "",
    categoria: "Componente de PC",
    titulo: "Fuente de alimentación EVGA SuperNOVA 850 G5",
    precio: 150,
    marca: "EVGA",
    tipo_producto: "Fuente de alimentación",
  },
  {
    id: 406,
    img: "",
    categoria: "Componente de PC",
    titulo: "Refrigeración líquida Corsair Hydro Series H100i",
    precio: 120,
    marca: "Corsair",
    tipo_producto: "Refrigeración líquida",
  },
  {
    id: 407,
    img: "",
    categoria: "Componente de PC",
    titulo: "Caja de PC NZXT H510",
    precio: 80,
    marca: "NZXT",
    tipo_producto: "Caja de PC",
  },
  {
    id: 408,
    img: "",
    categoria: "Componente de PC",
    titulo: "Ventiladores para PC Noctua NF-A14 PWM",
    precio: 25,
    marca: "Noctua",
    tipo_producto: "Ventilador para PC",
  },
  {
    id: 409,
    img: "",
    categoria: "Componente de PC",
    titulo: "Tarjeta de sonido externa Creative Sound BlasterX G6",
    precio: 150,
    marca: "Creative",
    tipo_producto: "Tarjeta de sonido",
  },
];

export default function getProducts() {
  return new Promise((res) => {
    setTimeout(() => res(productos), 999);
  });
}
